### ISSUE TITLE
No significant changes if patch the release

### ISSUE THREAD

**Issue by Innei** [antfu/changelogithub#15]
This is my config, first use `actions/create-release@v1` create release and this action will output a upload_url for next step which upload asset, and then `npx changelogithub` will got `No significant changes`.

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/41265413/174488364-e1840190-a20c-4592-9ab2-9abc7aa97011.png">

<img width="976" alt="image" src="https://user-images.githubusercontent.com/41265413/174488408-a6b96e53-04c0-4e85-837b-0a8fe28b4ec0.png">

It compare:
```
0b8521fe555b4cd47c93e4a051ac197d8d4d4506 -> v3.31.0 (0 commits)
```

v3.31.0 hash is `0b8521fe555b4cd47c93e4a051ac197d8d4d4506`, so compare itself with itself. and got nothing else.

```yaml

     - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - run: npx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release-${{ matrix.os }}.zip
          asset_content_type: application/zip
```
