### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by walmartwarlord** [antfu/changelogithub#24]
Hello! Sorry if this is not related to the repo but I hope it's ok that I ask this here.

In [this](https://github.com/antfu/changelogithub#usage) example GitHub action usage.. do we need to set the token for `${{secrets.GITHUB_TOKEN}}` somewhere? 

This happens whenever I try to do a release...

```bash
Run npx changelogithub
npm WARN exec The following package was not found and will be installed: changelogithub
changelogithubv0.12.1
v0.2.11 -> v0.2.1[2](https://github.com/walmartwarlord/foodapp/runs/7167987099?check_suite_focus=true#step:4:7) (1 commits)
--------------
--------------
Creating release notes...
FetchError: 403 Forbidden (https://api.github.com/repos/walmartwarlord/foodapp/releases)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async sendRelease (file:///home/runner/.npm/_npx/b22f3b69[8](https://github.com/walmartwarlord/foodapp/runs/7169182091?check_suite_focus=true#step:4:9)9da43b0/node_modules/changelogithub/dist/chunks/generate.mjs:28:15)
    at async CAC.<anonymous> (file:///home/runner/.npm/_npx/b22f3b69[9](https://github.com/walmartwarlord/foodapp/runs/7167987099?check_suite_focus=true#step:4:10)db43a0/node_modules/changelogithub/dist/cli.mjs:39:5)
Error: Process completed with exit code 1.
```

**Comment by antfu** [comment]
If you are using GitHub Actions and it's triggered by the correct event, the GITHUB_TOKEN will be generated automatically. If not you might go to `/settings/actions` to check your permission setting.

**Comment by walmartwarlord** [comment]
Thanks @antfu ! Is there something wrong with my permissions?

<img width="779" alt="Screen Shot 2022-07-03 at 2 27 31 PM" src="https://user-images.githubusercontent.com/72330740/177057806-6856b5ed-a8d0-477c-bd89-ebe1ba54d11c.png">

**Comment by yunsii** [comment]
Add **permissions** to release job is a better solution:

```yaml
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    # ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
