### ISSUE TITLE
After releasing returns the new created release id.

### ISSUE THREAD

**Issue by orangelckc** [antfu/changelogithub#30]
### Clear and concise description of the problem

Is it possible to get the release id after success updating the changelog? 
By [create-release](https://github.com/actions/create-release), it returns some outputs.
By using the release id, i can do further build like [this](https://github.com/tauri-apps/tauri-action).

Or is there any other way to generate the changelog and to release builds at the same time?
Thanks!

### Suggested solution

Noting to suggest on codes. Just wish to simplify the process of releasing and building.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jbaubree** [comment]
+1 ! In my side, this idea will be helpful

**Comment by HiDeoo** [comment]
Had the same requirement multiple times and to make it easier until ([and if](https://github.com/antfu/changelogithub/issues/5#issuecomment-1154179110)) this is supported, I created a [small GitHub Action](https://github.com/HiDeoo/changelogithub-action) which is just a wrapper around `changelogithub` and provides the *release ID*, *release URL* and *release upload URL* as output variables, e.g. `steps.changelog.outputs.release_id`:

```yaml
- uses: hideoo/changelogithub-action@v1
  id: changelog
  with:
    token: ${{ secrets.GITHUB_TOKEN }}

- name: Get the release ID
  run: echo "The release ID is ${{ steps.changelog.outputs.release_id }}"
```
