### ISSUE TITLE
Could I release a file with  changelogithub?

### ISSUE THREAD

**Issue by s3xysteak** [antfu/changelogithub#44]
### Clear and concise description of the problem

To release with a file by `changelogithub`.
I am using it for a tauri-app and I want to release with a compiled file.

### Suggested solution

maybe like:
```
- run: npx changelogithub
  env:
    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  with:
    files: ['./dist/index.js', './src-tauri/target/release/app.exe']
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by s3xysteak** [comment]
I found [release-action](https://github.com/ncipollo/release-action) which can release with a file. But I still want the artical which `changelogithub` provides ❤️ .
Is there any solutions?
```
- uses: ncipollo/release-action@v1
  with:
    artifacts: "release.tar.gz,foo/*.txt"
    bodyFile: "body.md"
    token: ${{ secrets.YOUR_GITHUB_TOKEN }}
```
