### ISSUE TITLE
Name mentioned in the changelog of the GitHub release.

### ISSUE THREAD

**Issue by hacxy** [antfu/changelogithub#56]
### Describe the bug

Why is the organization name mentioned in the github release after I publish, instead of my own name, 

<img width="953" alt="image" src="https://github.com/user-attachments/assets/49e7bdaf-b0fc-4867-8526-49dcff92914d">

How did this organization get its name? Is this affected by GITHUB_TOKEN? If so, how should I adjust it?

### Reproduction

https://github.com/lakyjs/release-demo/releases/tag/v0.0.8

### System Info

```Shell
System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M2
    Memory: 142.50 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.16.0/bin/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
    pnpm: 9.6.0 - ~/.nvm/versions/node/v20.16.0/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.86
    Safari: 18.1.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hacxy** [comment]
This is the workflows: 

```yml
name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
